// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Data;

#nullable disable

namespace QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.DangKyDeTai", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<string>("GhiChuDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoDangKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDeTai")
                        .HasColumnType("int");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaDeTai");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("DangKyDeTais");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.DeTai", b =>
                {
                    b.Property<int>("MaDeTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDeTai"));

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int>("MaLinhVuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.Property<int>("SoSinhVienToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenDeTai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YeuCau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDeTai");

                    b.HasIndex("MaLinhVuc");

                    b.ToTable("DeTais");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.GiangVien", b =>
                {
                    b.Property<string>("MaGiangVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HocVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaLinhVuc")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoSinhVienHuongDanToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("MaLinhVuc");

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.LinhVuc", b =>
                {
                    b.Property<int>("MaLinhVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLinhVuc"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLinhVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLinhVuc");

                    b.ToTable("LinhVucs");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.PhanCongHuongDan", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDangKy")
                        .HasColumnType("int");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaDangKy");

                    b.HasIndex("MaGiangVien");

                    b.ToTable("PhanCongHuongDans");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Khoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.DangKyDeTai", b =>
                {
                    b.HasOne("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.DeTai", "DeTai")
                        .WithMany("DangKyDeTais")
                        .HasForeignKey("MaDeTai")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyDeTais")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeTai");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.DeTai", b =>
                {
                    b.HasOne("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.LinhVuc", "LinhVuc")
                        .WithMany("DeTais")
                        .HasForeignKey("MaLinhVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhVuc");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.GiangVien", b =>
                {
                    b.HasOne("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.LinhVuc", "LinhVuc")
                        .WithMany("GiangViens")
                        .HasForeignKey("MaLinhVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhVuc");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.PhanCongHuongDan", b =>
                {
                    b.HasOne("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.DangKyDeTai", "DangKyDeTai")
                        .WithMany("PhanCongHuongDans")
                        .HasForeignKey("MaDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.GiangVien", "GiangVien")
                        .WithMany("PhanCongHuongDans")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DangKyDeTai");

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("SinhVien")
                        .HasForeignKey("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.SinhVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.DangKyDeTai", b =>
                {
                    b.Navigation("PhanCongHuongDans");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.DeTai", b =>
                {
                    b.Navigation("DangKyDeTais");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.GiangVien", b =>
                {
                    b.Navigation("PhanCongHuongDans");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.LinhVuc", b =>
                {
                    b.Navigation("DeTais");

                    b.Navigation("GiangViens");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.SinhVien", b =>
                {
                    b.Navigation("DangKyDeTais");
                });

            modelBuilder.Entity("QuanLyDoAnPhanCongGV_UNETI12_TI17A1HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("SinhVien")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
